Add type annotations
adafruit/Adafruit_CircuitPython_MotorKit pull request #43
Opened 2022-03-20 18:06 UTC by tekktrik

Resolves #41

2022-03-21 16:12 UTC, FoamyGuy requested changes
looks mostly good to me, but one question on `pwm_frequency` in the places where it's typed.

2022-03-21 16:12 UTC, FoamyGuy commented on adafruit_motorkit.py
> +        pwm_frequency: float = 1600,
Should the default value here be `1600.0`? Or should the type be int? It's listed as float as well inside of PCA9685 library so I'm guessing that is correct and that we'd want 1600.0 here to match.

2022-03-21 16:12 UTC, FoamyGuy commented on adafruit_motorkit.py
> +    def frequency(self, pwm_frequency: float = 1600) -> None:
same 1600.0 here I think.

2022-03-21 17:29 UTC, tekktrik commented
Yup, good point on the defaults being `int`, flipped 'em to `float`!

2022-03-28 15:17 UTC, FoamyGuy approved these changes
looks good to me. Thanks @tekktrik

2022-03-28 15:17 UTC, merged